### ISSUE TITLE
Failure

### ISSUE THREAD

**Issue by felipe2006ml** [ServiceNow/devtraining-needit-quebec#120]
I forked the repo but i received the message: The user only has read access to the repo. Make sure the user has both read and write access

**Comment by alekhyamodi** [comment]
Even i am having same issue. Plz help if any solution.
I tried deleting the application. 
I tried configuring the Repository Configurations

Still getting the same error message:
 The user only has read access to the repo. Make sure the user has both read and write access

**Comment by felipe2006ml** [comment]
> Even i am having same issue. Plz help if any solution.
> I tried deleting the application.
> I tried configuring the Repository Configurations
> 
> Still getting the same error message:
> The user only has read access to the repo. Make sure the user has both read and write access

I got it, follow the steps below:
In GitHub go to Settings/Developer Settings/Personal Access Token and click on Button "Generate new token"
Fill the form:
Note - Name of Token
Expiration
Select Scopes - I marked all
After fill the form click on Generate Token and copy the token generated

On ServiceNow Credentials, create Basic Auth and instead of your github password use the generated token.

**Comment by alekhyamodi** [comment]
> 
> 
> > Even i am having same issue. Plz help if any solution.
> > I tried deleting the application.
> > I tried configuring the Repository Configurations
> > Still getting the same error message:
> > The user only has read access to the repo. Make sure the user has both read and write access
> 
> I got it, follow the steps below:
> In GitHub go to Settings/Developer Settings/Personal Access Token and click on Button "Generate new token"
> Fill the form:
> Note - Name of Token
> Expiration
> Select Scopes - I marked all
> After fill the form click on Generate Token and copy the token generated
> 
> On ServiceNow Credentials, create Basic Auth and instead of your github password use the generated token.

Thanks a lot. I did the same too :) 
I enabled the 2FA and generated Personal Access Token and used the token as password in "Credentials" module for Github.

Thanks for the reply once again.

**Comment by trixie5120** [comment]
> I forked the repo but i received the message: The user only has read access to the repo. Make sure the user has both read and write access

having the same issue all of a sudden
