### ISSUE TITLE
Failure

### ISSUE THREAD

**Issue by Yashbs** [ServiceNow/devtraining-needit-quebec#121]
I am unable to commit, create a branch or fork the branch, I am getting error "The user only has read access to the repo. Make sure the user has both read and write access"

**Comment by Yashbs** [comment]
Go to Settings> developer settings> generate personal token> select all and use the token as password for the cred in Servicenow.

**Comment by bsweets** [comment]
I am sorry you ran into an issue. GitHub recently made a change that requires users to use a personal access token when authenticating via an API, as you do with ServiceNow. I am in the process of updating all our instructions. If you need more information, you can find more in the new [Authenticating to GitHub](https://developer.servicenow.com/dev.do#!/guides/quebec/developer-program/github-guide/using-servicenow-provided-application-repositories#authenticating-to-github) section of our GitHub Guide.
